name: Java CI/CD with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Make deploy directory
      run: mkdir deploy

    - name: Copy jar to deploy directory
      run: cp ./build/libs/*.jar ./deploy/

    - name: Zip jar file
      run: zip -r -qq -j ./springboot-ci-cd.zip ./deploy

    - name: Deliver to AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp \
        --region ap-northeast-2 \
        --acl private \
        ./springboot-ci-cd.zip s3://github-action-deploy-spring/

    - name: Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws deploy create-deployment \
        --application-name codedeploy-spring-ci-cd \
        --deployment-group-name deploy-group-spring-ci-cd \
        --file-exists-behavior OVERWRITE \
        --s3-location bucket=github-action-deploy-spring,bundleType=zip,key=springboot-ci-cd.zip \
        --region ap-northeast-2
